# Inherit from base config
defaults:
  - base_config

# Override specific settings for this CIFAR-10 test run
run_name: "sdxl_vae_cifar10_test_run"

# threshold to consider neuron as "dead"
threshold: 1e-5

# Data settings for CIFAR-10 test
data:
  dataset_name: "uoft-cs/cifar10" # Official HF ID for CIFAR-10
  image_column: "img"            # Correct image column for CIFAR-10
  resolution: 64                 # Use smaller resolution for faster dev run
  max_samples: 100               # Use only 100 samples for training
  batch_size: 8                  # Can use slightly larger BS for smaller images
  num_workers: 0                 # Use 0 workers for simplicity in test run

# Training settings for a quick test
training:
  num_train_epochs: 10           # Train for only 10 epoch
  learning_rate: 5e-5            # Might need slight adjustment for different data/res
  gradient_accumulation_steps: 1
  mixed_precision: "no"          # Use 'no' for CPU or if fp16 causes issues on small runs
  kl_weight: 1e-6                # Ensure KL weight is present if base default changes
  max_grad_norm: 1.0             # Ensure grad norm is present if base default changes

# Logging and Saving for quick test
logging:
  log_interval: 10               # Log more frequently
  report_to: "wandb"             # <<< Changed back to wandb
  # entity: "vae-dyn"            # Inherited from base_config
saving:
  save_interval: 50              # Save checkpoint relatively frequently
  checkpoint_dir_prefix: "chkpt" # Inherited, ensure present

# Ensure tracking/intervention are disabled for this test
tracking:
  enabled: false
classification:
  enabled: false
intervention:
  enabled: false

